---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "latest"
inputs:
  - name: cpi-release-src
outputs:
  - name: terraform-env
run:
  path: cpi-release-src/ci/tasks/prepare-terraform-env.sh

params:
  oracle_apikey:
