---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((docker-repo-name))/ubuntu-xenial-boshcliv2
    tag: "latest"
inputs:
  - name: cpi-release-src
  - name: candidate
  - name: oci-config
  - name: stemcell
  - name: bosh-deployment
outputs:
  - name: deployment
run:
  path: cpi-release-src/ci/tasks/setup-director.sh
params:
  BOSH_LOG_LEVEL:                 debug
  BOSH_LOG_PATH:                  ./bosh.log
